config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users

  resources :items, only: [:index, :new, :create]
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    load_items
  end

  def new
    build_item
  end

  def create
    build_item
    save_item or render 'new'
  end

  private

  def load_items
    @items ||= item_scope.to_a
  end

  def build_item
    @item ||= item_scope.build
    @item.attributes = item_params
  end

  def save_item
    if @item.save
      redirect_to items_url
    end
  end

  def item_params
    item_params = params[:item]
    item_params ? item_params.permit(:name) : {}
  end

  def item_scope
    Item.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
<div class="row">
  <div class="small-6 small-centered columns end">
    <div class="row">
      <div class="small-12 columns">
        <h1>My Items</h1>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <%= link_to 'Add Item', new_item_path, {class: 'button tiny'} %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <table class="items">
          <tr>
            <th>Name</th>
          </tr>
          <% @items.each do |item| %>
            <tr class="item">
              <td class="item-name"><%= item.name %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="row">
  <div class="small-6 small-centered columns end">
    <div class="row">
      <div class="small-12 columns end">
        <h1>Add Item</h1>
      </div>
    </div>
    <% if @item.errors.any? %>
      <div class="row">
        <div class="small-12 columns end">
          <div id="error_explanation">
            <ul>
              <% @item.errors.full_messages.each do |error| %>
                <%= content_tag :li, error %>
              <% end %>
            </ul>

          </div>
        </div>
      </div>
    <% end %>
    <%= form_for @item do |f| %>
      <div class="row">
        <div class="small-12 columns end">
          <fieldset>
            <%= f.label :name %>
            <%= f.text_field :name, {autofocus: 'autofocus'} %>
          </fieldset>
        </div>
      </div>
      <div class="row">
        <div class="small-2 columns end">
          <%= f.submit 'Create', {class: 'button tiny default'} %>
        </div>
        <div class="small-10 columns">
          <%= link_to 'Cancel', items_path, {class: 'button tiny secondary'} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "loan app" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="fixed">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <%= link_to 'Loan', root_path %>
            </h1>
          </li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <% if user_signed_in? %>
              <li class="has-dropdown">
                <a href="#">
                  <span class="user_name"><%= current_user.email %></span>
                </a>
                <ul class="dropdown">
                  <li>
                    <%= link_to 'My Items', items_path %>
                  </li>
                </ul>
              </li>
              <li class="has-form">
                <%= link_to 'Log out', 'users/sign_out', method: :delete, class: 'button alert' %>
              </li>
            <% end %>
          </ul>
        </section>
      </nav>
    </div>

    <br/>

    <div class="row">
      <div class="column small-12">
        <% if notice.present? %>
          <div data-alert class="alert-box success radius">
            <%= notice %>
          </div>
        <% end %>
        <% if alert.present? %>
          <div data-alert class="alert-box alert radius">
            <%= alert %>
          </div>
        <% end %>
      </div>
    </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="row">
  <div class="column small-12">
    <h1>Hey there</h1>  
  </div>
</div>